### PR TITLE
pants: upgrade Pants to 2.21.0

### PR DESCRIPTION
**Pull request by AlexTereshenkov**

### CODE REVIEW

**Comment by sureshjoshi** [comment]
Wait, what? Aren't we already on 2.21?
Screenshot 2024-06-20 at 17 40 50

**Comment by huonw** [comment]
It does look like #17 did this already, but we forgot to update https://github.com/pantsbuild/pants/issues/20970. Thanks @AlexTereshenkov, sorry for the wasted work!

**Comment by sureshjoshi** [comment]
> but we forgot to update

Yep, that sounds like me...

**Comment by kaos** [comment]
lesson to learn here: make sure your branch is up-to-date before branching out ;)

**Pull request closed without merging**
