### PR TITLE
Add example using GHA cache backend

### PR DESCRIPTION
**Pull request by riisi**
Raising for info at this stage pending 2.19 release. 

Note that no changes are required to run this locally - i.e. it will not fail due to missing GH tokens but fall back to local cache if present. 

I think I will also attempt to add an example using the Inline cache backend, publishing to Github packages - this seems a better option when there are many images as the GHA cache limit would be reached.

### CODE REVIEW

**Review by benjyw — APPROVED** [review]
Very cool! I'll ask @kaos to take a quick look as well.

**Review by kaos — APPROVED** [review]
lgtm.

I'm not familiar with the values for `cache_from` and `cache_to` in particular, but trust they do what is intended ;)

**Comment by benjyw** [comment]
@riisi this is still a Draft. Should it be?

**Comment by riisi** [comment]
Initially because this needs pants v2.19. But also will change slightly with some fixes to Docker backend that I’m working on now. Would hold off on merging for now.  On 9 Nov 2023, at 23:30, Benjy Weinberger ***@***.***> wrote:﻿
@riisi this is still a Draft. Should it be?

**Comment by huonw** [comment]
2.19 is released. Is this ready to go again?

**Comment by riisi** [comment]
I think this should be good to go now.

**Pull request merged**
