### PR TITLE
pants: upgrade Pants to 2.16.0

### PR DESCRIPTION
**Pull request by AlexTereshenkov**
Upgrade to Pants 2.16.0

### CODE REVIEW

**Comment by AlexTereshenkov** [comment]
@kaos how interesting, the tailor fails. Tailor works fine in a local checkout. I thought it's placing `pants` binary launcher and Pants thinks it's an executable, but this doesn't happen locally (when placing `pants` binary file there).

Anything that draws your attention immediately, since you've built this project? :)

**Comment by kaos** [comment]
no idea why this would behave any different than for the other example repos.

**Comment by AlexTereshenkov** [comment]
Figured it out - the `get-pants.sh` is left in the root after the Pants bootstrapping. Removing it after the bootstrap solves the problem.

**Review by huonw — APPROVED** [review]
Looks good. Maybe `get-pants.sh` should be checked in? Per https://www.pantsbuild.org/docs/installation

> Instead, for regular use, we recommend checking this script into the root of your repo and pointing users and CI machines to that checked-in version

**Pull request merged**
